### PR TITLE
feat: local + algolia search

### LINKED ISSUE #8: Algolia Plugin
In my experience this is the easiest way to add an awesome search experience to your site. There's prior art in [Vitepress](https://vitepress.vuejs.org/) we can look at.

image

### PR DESCRIPTION
**Pull request by Soya-xy**
Hello, this is my first time pr. 
Directory search, algolia search, event output highlighting and mouse position field are added.
I'm not sure whether my code meets the standard. If there is anything wrong, please point out.

closes #8, #9.

### CODE REVIEW

**Comment by mihar-22** [comment]
This is awesome @Soya-xy!! In the future it would be nice to split this PR up, as there's a few separate issues being tackled at once. Another thing, it'd be best to first create an issue for any work that doesn't have one such as event highlighting.

Since the PR is a little big, just give me some time to review it 😄 

Thanks again 🥳

**Comment by Soya-xy** [comment]
> 这太棒了@Soya-xy！将来最好将这个 PR 分开，因为有几个单独的问题要同时解决。另一件事，最好先为任何没有问题的工作创建一个问题，例如事件突出显示。
> 
> 由于PR有点大，请给我一些时间来审查它 😄
> 
> 再次感谢 🥳

Thank you. I see

**Comment by Soya-xy** [comment]
When I pull the main branch. After creating a svelte TS template, it is found that the `vite-plugin-svelte` import type reports an error. I don't know whether it's my environment or the version. There was no such error report before
image

**Comment by mihar-22** [comment]
Sorry about that, I recently removed the `esbuild` Svelte preprocessor from the client package. We now let Vite preprocess Svelte files. You'll need to update your configuration, see [this example](https://github.com/vitebook/vitebook/blob/main/examples/svelte/.vitebook/config.ts#L16-L22).

**Comment by mihar-22** [comment]
Just an update that I'm working on refactoring this slowly, and hope to have some good notes for you soon @Soya-xy. We'll get this merged in once I push the changes up 👍

**Comment by mihar-22** [comment]
Closing due to conflicts, sorry about not merging this in earlier Soya!

**Pull request closed without merging**
